export const YUNWU_PROVIDERS = {
  'yunwu-seedance': {
    id: 'yunwu-seedance',
    typeId: 'seedance',
    typeLabel: 'Seedance',
    selectorLabel: 'seedance1.5pro',
    name: 'Seedance 1.5 Pro',
    vendor: 'Yunwu API',
    color: '#1d4ed8',
    models: [
      { value: 'doubao-seedance-1-0-lite-t2v-250428', label: 'Seedance 1.0 Lite T2V', tag: 'Yunwu' },
      { value: 'doubao-seedance-1-0-lite-i2v-250428', label: 'Seedance 1.0 Lite I2V', tag: 'Yunwu' },
      { value: 'doubao-seedance-1-0-pro-250528', label: 'Seedance 1.0 Pro', tag: 'Yunwu' },
      { value: 'doubao-seedance-1-0-pro-fast-251015', label: 'Seedance 1.0 Pro Fast', tag: 'Yunwu' },
      { value: 'doubao-seedance-1-5-pro-251215', label: 'Seedance 1.5 Pro', tag: 'Yunwu' },
      { value: 'doubao-seedance-2-0-260128', label: 'Seedance 2.0', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    resolutions: {
      default: ['480p'],
    },
    durations: [5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      watermark: true,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
      { value: 'i2v', label: '图生视频' },
      { value: 'flf', label: '首尾帧' },
      { value: 'ref', label: '参考图片' },
    ],
    modeModels: {
      t2v: [
        'doubao-seedance-1-0-lite-t2v-250428',
        'doubao-seedance-1-0-pro-250528',
        'doubao-seedance-1-0-pro-fast-251015',
        'doubao-seedance-1-5-pro-251215',
        'doubao-seedance-2-0-260128',
      ],
      i2v: [
        'doubao-seedance-1-0-lite-i2v-250428',
        'doubao-seedance-1-0-pro-250528',
        'doubao-seedance-1-0-pro-fast-251015',
        'doubao-seedance-1-5-pro-251215',
        'doubao-seedance-2-0-260128',
      ],
      flf: [
        'doubao-seedance-1-0-lite-i2v-250428',
        'doubao-seedance-1-0-pro-250528',
        'doubao-seedance-1-0-pro-fast-251015',
        'doubao-seedance-1-5-pro-251215',
        'doubao-seedance-2-0-260128',
      ],
      ref: [
        'doubao-seedance-1-0-lite-i2v-250428',
        'doubao-seedance-1-0-pro-250528',
        'doubao-seedance-1-0-pro-fast-251015',
        'doubao-seedance-1-5-pro-251215',
        'doubao-seedance-2-0-260128',
      ],
    },
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
      i2v: 1,
      flf: 2,
      ref: 5,
    },
    defaults: {
      model: 'doubao-seedance-1-5-pro-251215',
      aspectRatio: '16:9',
      resolution: '480p',
      duration: 5,
      sampleCount: 1,
      generateAudio: false,
      watermark: false,
    },
    backendKind: 'yunwu',
  },
  'yunwu-veo': {
    id: 'yunwu-veo',
    typeId: 'veo',
    typeLabel: 'Veo',
    selectorLabel: 'veo3',
    name: 'Veo (Yunwu)',
    vendor: 'Yunwu API',
    color: '#6d28d9',
    models: [
      { value: 'veo2', label: 'Veo 2', tag: 'Yunwu' },
      { value: 'veo2-fast', label: 'Veo 2 Fast', tag: 'Yunwu' },
      { value: 'veo2-fast-frames', label: 'Veo 2 Fast Frames', tag: 'Yunwu' },
      { value: 'veo2-fast-components', label: 'Veo 2 Fast Components', tag: 'Yunwu' },
      { value: 'veo2-pro', label: 'Veo 2 Pro', tag: 'Yunwu' },
      { value: 'veo2-pro-components', label: 'Veo 2 Pro Components', tag: 'Yunwu' },
      { value: 'veo3', label: 'Veo 3', tag: 'Yunwu' },
      { value: 'veo3-fast', label: 'Veo 3 Fast', tag: 'Yunwu' },
      { value: 'veo3-fast-frames', label: 'Veo 3 Fast Frames', tag: 'Yunwu' },
      { value: 'veo3-frames', label: 'Veo 3 Frames', tag: 'Yunwu' },
      { value: 'veo3-pro', label: 'Veo 3 Pro', tag: 'Yunwu' },
      { value: 'veo3-pro-frames', label: 'Veo 3 Pro Frames', tag: 'Yunwu' },
      { value: 'veo3.1', label: 'Veo 3.1', tag: 'Yunwu' },
      { value: 'veo3.1-components', label: 'Veo 3.1 Components', tag: 'Yunwu' },
      { value: 'veo3.1-fast', label: 'Veo 3.1 Fast', tag: 'Yunwu' },
      { value: 'veo3.1-pro', label: 'Veo 3.1 Pro', tag: 'Yunwu' },
      { value: 'veo3.1-4k', label: 'Veo 3.1 4K', tag: 'Yunwu' },
      { value: 'veo3.1-pro-4k', label: 'Veo 3.1 Pro 4K', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16'],
    resolutions: {
      default: ['720p'],
      'veo3.1-4k': ['4k'],
      'veo3.1-pro-4k': ['4k'],
    },
    durations: [4, 6, 8],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      enhancePrompt: true,
      enableUpsample: true,
    },
    generationModes: [
      { value: 'ref', label: '参考图片' },
    ],
    modeModels: {
      ref: [
        'veo3.1-components',
      ],
    },
    referenceInputMode: 'url',
    maxReferenceImages: {
      ref: 2,
    },
    defaults: {
      model: 'veo3.1-components',
      aspectRatio: '9:16',
      resolution: '720p',
      duration: 8,
      sampleCount: 1,
      enhancePrompt: true,
      enableUpsample: true,
    },
    backendKind: 'yunwu',
  },
  'yunwu-kling': {
    id: 'yunwu-kling',
    typeId: 'kling',
    typeLabel: 'Kling',
    selectorLabel: 'kling2',
    name: 'Kling (Yunwu)',
    vendor: 'Yunwu API',
    color: '#ea580c',
    models: [
      { value: 'kling-v1', label: 'Kling v1', tag: 'Yunwu' },
      { value: 'kling-v1-5', label: 'Kling v1.5', tag: 'Yunwu' },
      { value: 'kling-v1-6', label: 'Kling v1.6', tag: 'Yunwu' },
      { value: 'kling-v2', label: 'Kling v2', tag: 'Yunwu' },
      { value: 'kling-v2-master', label: 'Kling v2 Master', tag: 'Yunwu' },
      { value: 'kling-v2-1', label: 'Kling v2.1', tag: 'Yunwu' },
      { value: 'kling-v2-1-master', label: 'Kling v2.1 Master', tag: 'Yunwu' },
      { value: 'kling-v2-5-turbo', label: 'Kling v2.5 Turbo', tag: 'Yunwu' },
      { value: 'kling-v2-6', label: 'Kling v2.6', tag: 'Yunwu' },
      { value: 'kling-v3', label: 'Kling v3', tag: 'Yunwu' },
      { value: 'kling-video-o1', label: 'Kling Video O1', tag: 'Yunwu' },
      { value: 'kling-v3-omni', label: 'Kling v3 Omni', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: {
      default: ['720p'],
    },
    durations: [3, 5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: true,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
      { value: 'i2v', label: '图生视频' },
      { value: 'flf', label: '首尾帧' },
      { value: 'ref', label: '参考图片' },
      { value: 'omni', label: '全模态参考' },
    ],
    modeModels: {
      ref: ['kling-v1-6'],
      omni: ['kling-video-o1'],
    },
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
      i2v: 1,
      flf: 2,
      ref: 4,
      omni: 1,
    },
    maxReferenceVideos: {
      omni: 1,
    },
    defaults: {
      model: 'kling-v3',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
      generateAudio: false,
    },
    backendKind: 'yunwu',
  },
  'yunwu-sora': {
    id: 'yunwu-sora',
    typeId: 'sora',
    typeLabel: 'Sora',
    selectorLabel: 'sora1',
    name: 'Sora (Yunwu)',
    vendor: 'Yunwu API',
    color: '#0f766e',
    models: [
      { value: 'sora-2', label: 'Sora 2', tag: 'Yunwu' },
      { value: 'sora-2-pro', label: 'Sora 2 Pro', tag: 'Yunwu' },
      { value: 'sora-2-all', label: 'Sora 2 All', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5, 10, 15],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      watermark: true,
      privateOutput: true,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
      { value: 'i2v', label: '图生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
      i2v: 1,
    },
    defaults: {
      model: 'sora-2',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 10,
      sampleCount: 1,
      watermark: false,
      privateOutput: true,
    },
    backendKind: 'yunwu',
  },
  'yunwu-hailuo': {
    id: 'yunwu-hailuo',
    typeId: 'hailuo',
    typeLabel: 'Hailuo',
    selectorLabel: 'hailuo1',
    name: 'Hailuo (Yunwu)',
    vendor: 'Yunwu API',
    color: '#0891b2',
    models: [
      { value: 'MiniMax-Hailuo-02', label: 'MiniMax Hailuo 02', tag: 'Yunwu' },
      { value: 'MiniMax-Hailuo-2.3', label: 'MiniMax Hailuo 2.3', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16'],
    resolutions: {
      default: ['768P'],
    },
    durations: [6, 10],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      promptOptimizer: true,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
      { value: 'i2v', label: '图生视频' },
      { value: 'flf', label: '首尾帧' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
      i2v: 1,
      flf: 2,
    },
    defaults: {
      model: 'MiniMax-Hailuo-2.3',
      aspectRatio: '16:9',
      resolution: '768P',
      duration: 6,
      sampleCount: 1,
      promptOptimizer: true,
    },
    backendKind: 'yunwu',
  },
  'yunwu-luma': {
    id: 'yunwu-luma',
    typeId: 'luma',
    typeLabel: 'Luma',
    selectorLabel: 'luma1',
    name: 'Luma (Yunwu)',
    vendor: 'Yunwu API',
    color: '#7c2d12',
    models: [
      { value: 'ray-v2', label: 'Ray v2', tag: 'Yunwu' },
      { value: 'ray-v1', label: 'Ray v1', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: false,
      referenceVideo: false,
      referenceAudio: false,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
    },
    defaults: {
      model: 'ray-v2',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
    },
    backendKind: 'yunwu',
  },
  'yunwu-runway': {
    id: 'yunwu-runway',
    typeId: 'runway',
    typeLabel: 'Runway',
    selectorLabel: 'runway1',
    name: 'Runway (Yunwu)',
    vendor: 'Yunwu API',
    color: '#be123c',
    models: [
      { value: 'gen4_turbo', label: 'Gen-4 Turbo', tag: 'Yunwu' },
      { value: 'gen4', label: 'Gen-4', tag: 'Yunwu' },
      { value: 'gen3', label: 'Gen-3', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      watermark: true,
    },
    generationModes: [
      { value: 'i2v', label: '图生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      i2v: 1,
    },
    defaults: {
      model: 'gen4_turbo',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
      watermark: false,
    },
    backendKind: 'yunwu',
  },
  'yunwu-grok': {
    id: 'yunwu-grok',
    typeId: 'grok',
    typeLabel: 'Grok',
    selectorLabel: 'grok1',
    name: 'Grok Video (Yunwu)',
    vendor: 'Yunwu API',
    color: '#475569',
    models: [
      { value: 'grok-video-3', label: 'Grok Video 3', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: false,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
      { value: 'i2v', label: '图生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
      i2v: 1,
    },
    defaults: {
      model: 'grok-video-3',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
    },
    backendKind: 'yunwu',
  },
  'yunwu-wanxiang': {
    id: 'yunwu-wanxiang',
    typeId: 'wanxiang',
    typeLabel: 'Wanxiang',
    selectorLabel: 'wanxiang1',
    name: 'Wanxiang (Yunwu)',
    vendor: 'Yunwu API',
    color: '#16a34a',
    models: [
      { value: 'wan2.5-i2v-preview', label: 'Wan 2.5 I2V Preview', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5],
    sampleCounts: [1],
    features: {
      generateAudio: true,
      negativePrompt: false,
      referenceImage: true,
      referenceVideo: false,
      referenceAudio: false,
      promptExtend: true,
    },
    generationModes: [
      { value: 'i2v', label: '图生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      i2v: 1,
    },
    defaults: {
      model: 'wan2.5-i2v-preview',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
      generateAudio: false,
      promptExtend: true,
    },
    backendKind: 'yunwu',
  },
  'yunwu-tencent': {
    id: 'yunwu-tencent',
    typeId: 'tencent',
    typeLabel: 'Tencent',
    selectorLabel: 'tencent1',
    name: 'Tencent AIGC (Yunwu)',
    vendor: 'Yunwu API',
    color: '#2563eb',
    models: [
      { value: '1.6', label: 'Kling 1.6', tag: 'Yunwu' },
    ],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: {
      default: ['720p'],
    },
    durations: [5, 10],
    sampleCounts: [1],
    features: {
      generateAudio: true,
      negativePrompt: false,
      referenceImage: false,
      referenceVideo: false,
      referenceAudio: false,
    },
    generationModes: [
      { value: 't2v', label: '文生视频' },
    ],
    referenceInputMode: 'url',
    maxReferenceImages: {
      t2v: 0,
    },
    defaults: {
      model: '1.6',
      aspectRatio: '16:9',
      resolution: '720p',
      duration: 5,
      sampleCount: 1,
      generateAudio: false,
    },
    backendKind: 'yunwu',
  },
}

export const YUNWU_PROVIDER_ORDER = [
  'yunwu-seedance',
  'yunwu-veo',
]
